### ISSUE TITLE
bug: Horizontal scroll

### ISSUE THREAD

**Issue by craigcook** [skycatchfire/stateofmozilla#1]
Something in the layout is overflowing the viewport by about 20px and causing a horizontal scrollbar, but I haven't been able to find what actually causes it or even to isolate it to a single section or element.

![image](https://github.com/skycatchfire/stateofmozilla/assets/205591/cbf25a37-ec02-4ade-892c-c36c28a0b37b)

**Comment by wuebkers** [comment]
@craigcook I have changed the 100vw to 100%, let me know if you are still seeing this issue!

**Comment by craigcook** [comment]
Yes, it's still happening. You can reproduce this by turning on scrollbars in macos or just testing in Windows. 

I think I've isolated it to the left padding on the "Why Mozilla" section. Removing that padding fixes the horizontal scroll. But I'm not sure of the best way to get the scroll indicator effect without that padding to preserve space for it. It might need some other inner container to take the padding and prevent the outer container from being pushed wider than the window.

**Comment by wuebkers** [comment]
@craigcook I have pushed a fix (hopefully), and tested it on Windows and with the scrollbars always on if macOS. Please confirm that this issue is resolved!

**Comment by craigcook** [comment]
Woot! Looks like that did the trick.
